use_frameworks!

platform :ios, '9.0'

target 'KSCategory_Example' do
  pod 'KSCategory', :path => '../'

  target 'KSCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
